---
- hosts: all
  become: true
  vars:
    - ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Shutdown ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian" #ubuntu machine
       ansible_facts['os_family'] == "RedHat" #ec2_user machine

      #  tasks:
      # - name: Print all ansible gathered ansible_facts
      #ansible.builtin.debug:
      # var: ansible_facts
      #
    
