--- 
- hosts: localhost
  connection: local
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "login"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
      - { image: "ami-0e2c8caa4b6378d8c", name: "mange_ubuntu_node-1" }
      - { image: "ami-0e2c8caa4b6378d8c", name: "mange_ubuntu_node-2" }
      - { image: "ami-04b70fa74e45c3917", name: "mange_linux_node" }
      
